#lang ivy1.8

module vector(range) = { 
    type this

    action get(a:this,x:nat) returns (y:range)
    action set(a:this,x:nat,y:range) returns (a:this)
    action empty returns (a: this)
    action append(a: this, x: range) returns (y: this)

    action end(a: this) returns (len: nat)
}

module option(range) = {
    type this
    alias t = this

    function is_empty(X: t): bool
    function contents(X: t): range
}
